TASK:
  SOURCE: 'en'
  TARGET: 'it'
MODEL:
  BATCH_SIZE: 1
  LOG_FREQUENCY: 2
  LR: 0.0001
  MAX_SEQ_LEN: 315
  EMB_DIM: 256
  FF_HIDDEN_LAYER: 1024
  HEADS: 4
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  SCHEDULER_STEP_SIZE: 6
  GAMMA: 1e-1
  WORKERS: 1
  EPOCHS: 51
  STACK_ENC_DEC: 6
  LABEL_SMOOTHING: 0.1