TASK:
  SOURCE: 'en'
  TARGET: 'it'
MODEL:
  BATCH_SIZE: 16
  LOG_FREQUENCY: 2
  LR: 0.001
  MAX_SEQ_LEN: 512
  EMB_DIM: 128
  FF_HIDDEN_LAYER: 256
  HEADS: 8
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  GAMMA: 1e-1
  WORKERS: 4
  EPOCHS: 100
  STACK_ENC_DEC: 6
  LABEL_SMOOTHING: 0.1


